using System.ComponentModel.DataAnnotations;

namespace ITHelpdeskSystem.Models
{
    // Represents a single IT support request.
    public class Ticket
    {
        // Unique ticket identifier generated by the database.
        public int Id { get; set; }

        [Required(ErrorMessage = "Requester name is required.")]
        [StringLength(100)]
        [Display(Name = "Requester Name")]
        public string RequesterName { get; set; } = string.Empty;

        [Required(ErrorMessage = "Requester email is required.")]
        [EmailAddress(ErrorMessage = "Enter a valid email address.")]
        [StringLength(150)]
        [Display(Name = "Requester Email")]
        public string RequesterEmail { get; set; } = string.Empty;

        [Required(ErrorMessage = "Title is required.")]
        [StringLength(150)]
        public string Title { get; set; } = string.Empty;

        [Required(ErrorMessage = "Description is required.")]
        [StringLength(1000)]
        public string Description { get; set; } = string.Empty;

        // Priority remains unassigned until an Admin completes triage.
        public TicketPriority Priority { get; set; }
            = TicketPriority.Unassigned;

        // A newly submitted ticket begins in the Open state.
        public TicketStatus Status { get; set; }
            = TicketStatus.Open;

        [Display(Name = "Assigned Technician")]
        public string? AssignedTechnician { get; set; }

        public DateTime CreatedAt { get; set; }

        // Recorded when priority and technician assignment are completed.
        public DateTime? TriagedAt { get; set; }

        // Recorded when the issue is marked as resolved.
        public DateTime? ResolvedAt { get; set; }
    }
}
